version: '3.9'
services:
   rest-api:
      container_name: auth-app-backend
      restart: unless-stopped
      env_file: .env
      environment:
         - NODE_ENV=production
      build:
         context: ./
