### server
GET https://localhost:5900


### unknown route
GET https://localhost:5900/unknown

### api v1 routes health-check
GET https://localhost:5900/v1/healthCheck


### user register
POST https://localhost:5900/v1/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@gmail.com",
	"password": "test123"
}


### user login
POST https://localhost:5900/v1/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
	"password": "test123"
}


### user logout
DELETE  https://localhost:5900/v1/auth/logout
