### reverse geo-coding
POST http://localhost:5900/v1/location/reverse-geo-coding
Content-Type: application/json

{
    "latitude": 27.6627456,
	"longitude": 83.4699264
}


### get timezone id & country code
POST http://localhost:5900/v1/location/timezone
Content-Type: application/json

{
    "latitude": 27.6627456,
	"longitude": 83.4699264
}